version: '3.8'
services:

    # Redis
    redis:
        build: docker/redis
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        ports:
            - 6379:6379

    # ScyllaDB
    scylla:
        build: docker/scylla
        expose:
            - 9042
        ports:
            - 9042:9042

