version: '3.8'
services:

    # Redis
    redis:
        build: docker/redis
        container_name: game_03_redis
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        expose:
            - 6379
        ports:
            - 6379:6379

    # ScyllaDB
    scylla:
        build: docker/scylla
        container_name: game_03_scylla
        environment:
            - GOCQL_HOST_LOOKUP_PREFER_V4=true
        volumes:
            - ./docker/scylla/scylla.yaml:/etc/scylla/scylla.yaml
        command:
            - "--smp"
            - "2"
        expose:
            - 9042
        ports:
            - 9042:9042
