/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_gogo_protobuf_gogoproto_gogo_pb = require('../../../../../github.com/gogo/protobuf/gogoproto/gogo_pb.js');
var github_com_elojah_game_03_pkg_geometry_geometry_pb = require('../../../../../github.com/elojah/game_03/pkg/geometry/geometry_pb.js');
var github_com_elojah_game_03_pkg_ability_ability_pb = require('../../../../../github.com/elojah/game_03/pkg/ability/ability_pb.js');
goog.exportSymbol('proto.ability.Cast', null, global);
goog.exportSymbol('proto.ability.CastEffect', null, global);
goog.exportSymbol('proto.ability.CastTarget', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ability.CastTarget = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ability.CastTarget, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ability.CastTarget.displayName = 'proto.ability.CastTarget';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ability.CastTarget.prototype.toObject = function(opt_includeInstance) {
  return proto.ability.CastTarget.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ability.CastTarget} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.CastTarget.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId_asB64(),
    cellid: msg.getCellid_asB64(),
    rect: (f = msg.getRect()) && github_com_elojah_game_03_pkg_geometry_geometry_pb.Rect.toObject(includeInstance, f),
    circle: (f = msg.getCircle()) && github_com_elojah_game_03_pkg_geometry_geometry_pb.Circle.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ability.CastTarget}
 */
proto.ability.CastTarget.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ability.CastTarget;
  return proto.ability.CastTarget.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ability.CastTarget} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ability.CastTarget}
 */
proto.ability.CastTarget.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCellid(value);
      break;
    case 3:
      var value = new github_com_elojah_game_03_pkg_geometry_geometry_pb.Rect;
      reader.readMessage(value,github_com_elojah_game_03_pkg_geometry_geometry_pb.Rect.deserializeBinaryFromReader);
      msg.setRect(value);
      break;
    case 4:
      var value = new github_com_elojah_game_03_pkg_geometry_geometry_pb.Circle;
      reader.readMessage(value,github_com_elojah_game_03_pkg_geometry_geometry_pb.Circle.deserializeBinaryFromReader);
      msg.setCircle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ability.CastTarget.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ability.CastTarget.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ability.CastTarget} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.CastTarget.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getCellid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getRect();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      github_com_elojah_game_03_pkg_geometry_geometry_pb.Rect.serializeBinaryToWriter
    );
  }
  f = message.getCircle();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      github_com_elojah_game_03_pkg_geometry_geometry_pb.Circle.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes ID = 1;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastTarget.prototype.getId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes ID = 1;
 * This is a type-conversion wrapper around `getId()`
 * @return {string}
 */
proto.ability.CastTarget.prototype.getId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getId()));
};


/**
 * optional bytes ID = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getId()`
 * @return {!Uint8Array}
 */
proto.ability.CastTarget.prototype.getId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getId()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastTarget.prototype.setId = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes CellID = 2;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastTarget.prototype.getCellid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes CellID = 2;
 * This is a type-conversion wrapper around `getCellid()`
 * @return {string}
 */
proto.ability.CastTarget.prototype.getCellid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCellid()));
};


/**
 * optional bytes CellID = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCellid()`
 * @return {!Uint8Array}
 */
proto.ability.CastTarget.prototype.getCellid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCellid()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastTarget.prototype.setCellid = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional geometry.Rect Rect = 3;
 * @return {?proto.geometry.Rect}
 */
proto.ability.CastTarget.prototype.getRect = function() {
  return /** @type{?proto.geometry.Rect} */ (
    jspb.Message.getWrapperField(this, github_com_elojah_game_03_pkg_geometry_geometry_pb.Rect, 3));
};


/** @param {?proto.geometry.Rect|undefined} value */
proto.ability.CastTarget.prototype.setRect = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.ability.CastTarget.prototype.clearRect = function() {
  this.setRect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ability.CastTarget.prototype.hasRect = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional geometry.Circle Circle = 4;
 * @return {?proto.geometry.Circle}
 */
proto.ability.CastTarget.prototype.getCircle = function() {
  return /** @type{?proto.geometry.Circle} */ (
    jspb.Message.getWrapperField(this, github_com_elojah_game_03_pkg_geometry_geometry_pb.Circle, 4));
};


/** @param {?proto.geometry.Circle|undefined} value */
proto.ability.CastTarget.prototype.setCircle = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.ability.CastTarget.prototype.clearCircle = function() {
  this.setCircle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ability.CastTarget.prototype.hasCircle = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ability.Cast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ability.Cast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ability.Cast.displayName = 'proto.ability.Cast';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ability.Cast.prototype.toObject = function(opt_includeInstance) {
  return proto.ability.Cast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ability.Cast} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.Cast.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId_asB64(),
    abilityid: msg.getAbilityid_asB64(),
    targetsMap: (f = msg.getTargetsMap()) ? f.toObject(includeInstance, proto.ability.CastTarget.toObject) : [],
    at: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ability.Cast}
 */
proto.ability.Cast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ability.Cast;
  return proto.ability.Cast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ability.Cast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ability.Cast}
 */
proto.ability.Cast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAbilityid(value);
      break;
    case 3:
      var value = msg.getTargetsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.ability.CastTarget.deserializeBinaryFromReader, "");
         });
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ability.Cast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ability.Cast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ability.Cast} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.Cast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getAbilityid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getTargetsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.ability.CastTarget.serializeBinaryToWriter);
  }
  f = message.getAt();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional bytes ID = 1;
 * @return {!(string|Uint8Array)}
 */
proto.ability.Cast.prototype.getId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes ID = 1;
 * This is a type-conversion wrapper around `getId()`
 * @return {string}
 */
proto.ability.Cast.prototype.getId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getId()));
};


/**
 * optional bytes ID = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getId()`
 * @return {!Uint8Array}
 */
proto.ability.Cast.prototype.getId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getId()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.Cast.prototype.setId = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bytes AbilityID = 2;
 * @return {!(string|Uint8Array)}
 */
proto.ability.Cast.prototype.getAbilityid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes AbilityID = 2;
 * This is a type-conversion wrapper around `getAbilityid()`
 * @return {string}
 */
proto.ability.Cast.prototype.getAbilityid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAbilityid()));
};


/**
 * optional bytes AbilityID = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAbilityid()`
 * @return {!Uint8Array}
 */
proto.ability.Cast.prototype.getAbilityid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAbilityid()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.Cast.prototype.setAbilityid = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * map<string, CastTarget> Targets = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.ability.CastTarget>}
 */
proto.ability.Cast.prototype.getTargetsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.ability.CastTarget>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.ability.CastTarget));
};


proto.ability.Cast.prototype.clearTargetsMap = function() {
  this.getTargetsMap().clear();
};


/**
 * optional int64 At = 4;
 * @return {number}
 */
proto.ability.Cast.prototype.getAt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.ability.Cast.prototype.setAt = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ability.CastEffect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ability.CastEffect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ability.CastEffect.displayName = 'proto.ability.CastEffect';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ability.CastEffect.prototype.toObject = function(opt_includeInstance) {
  return proto.ability.CastEffect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ability.CastEffect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.CastEffect.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId_asB64(),
    self: jspb.Message.getFieldWithDefault(msg, 2, false),
    abilityid: msg.getAbilityid_asB64(),
    effectid: msg.getEffectid_asB64(),
    currentid: msg.getCurrentid_asB64(),
    effect: (f = msg.getEffect()) && github_com_elojah_game_03_pkg_ability_ability_pb.Effect.toObject(includeInstance, f),
    targetsMap: (f = msg.getTargetsMap()) ? f.toObject(includeInstance, proto.ability.CastTarget.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ability.CastEffect}
 */
proto.ability.CastEffect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ability.CastEffect;
  return proto.ability.CastEffect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ability.CastEffect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ability.CastEffect}
 */
proto.ability.CastEffect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSelf(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setAbilityid(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEffectid(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCurrentid(value);
      break;
    case 6:
      var value = new github_com_elojah_game_03_pkg_ability_ability_pb.Effect;
      reader.readMessage(value,github_com_elojah_game_03_pkg_ability_ability_pb.Effect.deserializeBinaryFromReader);
      msg.setEffect(value);
      break;
    case 7:
      var value = msg.getTargetsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.ability.CastTarget.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ability.CastEffect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ability.CastEffect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ability.CastEffect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ability.CastEffect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getSelf();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAbilityid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getEffectid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getCurrentid_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getEffect();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      github_com_elojah_game_03_pkg_ability_ability_pb.Effect.serializeBinaryToWriter
    );
  }
  f = message.getTargetsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.ability.CastTarget.serializeBinaryToWriter);
  }
};


/**
 * optional bytes ID = 1;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastEffect.prototype.getId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes ID = 1;
 * This is a type-conversion wrapper around `getId()`
 * @return {string}
 */
proto.ability.CastEffect.prototype.getId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getId()));
};


/**
 * optional bytes ID = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getId()`
 * @return {!Uint8Array}
 */
proto.ability.CastEffect.prototype.getId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getId()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastEffect.prototype.setId = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional bool Self = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.ability.CastEffect.prototype.getSelf = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.ability.CastEffect.prototype.setSelf = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bytes AbilityID = 3;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastEffect.prototype.getAbilityid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes AbilityID = 3;
 * This is a type-conversion wrapper around `getAbilityid()`
 * @return {string}
 */
proto.ability.CastEffect.prototype.getAbilityid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getAbilityid()));
};


/**
 * optional bytes AbilityID = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAbilityid()`
 * @return {!Uint8Array}
 */
proto.ability.CastEffect.prototype.getAbilityid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getAbilityid()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastEffect.prototype.setAbilityid = function(value) {
  jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional bytes EffectID = 4;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastEffect.prototype.getEffectid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes EffectID = 4;
 * This is a type-conversion wrapper around `getEffectid()`
 * @return {string}
 */
proto.ability.CastEffect.prototype.getEffectid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEffectid()));
};


/**
 * optional bytes EffectID = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEffectid()`
 * @return {!Uint8Array}
 */
proto.ability.CastEffect.prototype.getEffectid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEffectid()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastEffect.prototype.setEffectid = function(value) {
  jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional bytes CurrentID = 5;
 * @return {!(string|Uint8Array)}
 */
proto.ability.CastEffect.prototype.getCurrentid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes CurrentID = 5;
 * This is a type-conversion wrapper around `getCurrentid()`
 * @return {string}
 */
proto.ability.CastEffect.prototype.getCurrentid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCurrentid()));
};


/**
 * optional bytes CurrentID = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCurrentid()`
 * @return {!Uint8Array}
 */
proto.ability.CastEffect.prototype.getCurrentid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCurrentid()));
};


/** @param {!(string|Uint8Array)} value */
proto.ability.CastEffect.prototype.setCurrentid = function(value) {
  jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional Effect Effect = 6;
 * @return {?proto.ability.Effect}
 */
proto.ability.CastEffect.prototype.getEffect = function() {
  return /** @type{?proto.ability.Effect} */ (
    jspb.Message.getWrapperField(this, github_com_elojah_game_03_pkg_ability_ability_pb.Effect, 6));
};


/** @param {?proto.ability.Effect|undefined} value */
proto.ability.CastEffect.prototype.setEffect = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.ability.CastEffect.prototype.clearEffect = function() {
  this.setEffect(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.ability.CastEffect.prototype.hasEffect = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * map<string, CastTarget> Targets = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.ability.CastTarget>}
 */
proto.ability.CastEffect.prototype.getTargetsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.ability.CastTarget>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.ability.CastTarget));
};


proto.ability.CastEffect.prototype.clearTargetsMap = function() {
  this.getTargetsMap().clear();
};


goog.object.extend(exports, proto.ability);
