/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: github.com/elojah/game_03/pkg/entity/ability.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../../gogo/protobuf/gogoproto/gogo";
import * as pb_1 from "google-protobuf";
export namespace entity {
    export class Ability extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            EntityID?: Uint8Array;
            AbilityID?: Uint8Array;
            LastCast?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("EntityID" in data && data.EntityID != undefined) {
                    this.EntityID = data.EntityID;
                }
                if ("AbilityID" in data && data.AbilityID != undefined) {
                    this.AbilityID = data.AbilityID;
                }
                if ("LastCast" in data && data.LastCast != undefined) {
                    this.LastCast = data.LastCast;
                }
            }
        }
        get EntityID() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set EntityID(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get AbilityID() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set AbilityID(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get LastCast() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set LastCast(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            EntityID?: Uint8Array;
            AbilityID?: Uint8Array;
            LastCast?: number;
        }): Ability {
            const message = new Ability({});
            if (data.EntityID != null) {
                message.EntityID = data.EntityID;
            }
            if (data.AbilityID != null) {
                message.AbilityID = data.AbilityID;
            }
            if (data.LastCast != null) {
                message.LastCast = data.LastCast;
            }
            return message;
        }
        toObject() {
            const data: {
                EntityID?: Uint8Array;
                AbilityID?: Uint8Array;
                LastCast?: number;
            } = {};
            if (this.EntityID != null) {
                data.EntityID = this.EntityID;
            }
            if (this.AbilityID != null) {
                data.AbilityID = this.AbilityID;
            }
            if (this.LastCast != null) {
                data.LastCast = this.LastCast;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.EntityID.length)
                writer.writeBytes(1, this.EntityID);
            if (this.AbilityID.length)
                writer.writeBytes(2, this.AbilityID);
            if (this.LastCast != 0)
                writer.writeInt64(3, this.LastCast);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Ability {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Ability();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.EntityID = reader.readBytes();
                        break;
                    case 2:
                        message.AbilityID = reader.readBytes();
                        break;
                    case 3:
                        message.LastCast = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Ability {
            return Ability.deserialize(bytes);
        }
    }
}
