/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: github.com/elojah/game_03/pkg/entity/pc.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../../gogo/protobuf/gogoproto/gogo";
import * as pb_1 from "google-protobuf";
export namespace entity {
    export class PC extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            ID?: Uint8Array;
            UserID?: Uint8Array;
            WorldID?: Uint8Array;
            EntityID?: Uint8Array;
            At?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("ID" in data && data.ID != undefined) {
                    this.ID = data.ID;
                }
                if ("UserID" in data && data.UserID != undefined) {
                    this.UserID = data.UserID;
                }
                if ("WorldID" in data && data.WorldID != undefined) {
                    this.WorldID = data.WorldID;
                }
                if ("EntityID" in data && data.EntityID != undefined) {
                    this.EntityID = data.EntityID;
                }
                if ("At" in data && data.At != undefined) {
                    this.At = data.At;
                }
            }
        }
        get ID() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set ID(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get UserID() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set UserID(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get WorldID() {
            return pb_1.Message.getFieldWithDefault(this, 3, new Uint8Array(0)) as Uint8Array;
        }
        set WorldID(value: Uint8Array) {
            pb_1.Message.setField(this, 3, value);
        }
        get EntityID() {
            return pb_1.Message.getFieldWithDefault(this, 4, new Uint8Array(0)) as Uint8Array;
        }
        set EntityID(value: Uint8Array) {
            pb_1.Message.setField(this, 4, value);
        }
        get At() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set At(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            ID?: Uint8Array;
            UserID?: Uint8Array;
            WorldID?: Uint8Array;
            EntityID?: Uint8Array;
            At?: number;
        }): PC {
            const message = new PC({});
            if (data.ID != null) {
                message.ID = data.ID;
            }
            if (data.UserID != null) {
                message.UserID = data.UserID;
            }
            if (data.WorldID != null) {
                message.WorldID = data.WorldID;
            }
            if (data.EntityID != null) {
                message.EntityID = data.EntityID;
            }
            if (data.At != null) {
                message.At = data.At;
            }
            return message;
        }
        toObject() {
            const data: {
                ID?: Uint8Array;
                UserID?: Uint8Array;
                WorldID?: Uint8Array;
                EntityID?: Uint8Array;
                At?: number;
            } = {};
            if (this.ID != null) {
                data.ID = this.ID;
            }
            if (this.UserID != null) {
                data.UserID = this.UserID;
            }
            if (this.WorldID != null) {
                data.WorldID = this.WorldID;
            }
            if (this.EntityID != null) {
                data.EntityID = this.EntityID;
            }
            if (this.At != null) {
                data.At = this.At;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.ID.length)
                writer.writeBytes(1, this.ID);
            if (this.UserID.length)
                writer.writeBytes(2, this.UserID);
            if (this.WorldID.length)
                writer.writeBytes(3, this.WorldID);
            if (this.EntityID.length)
                writer.writeBytes(4, this.EntityID);
            if (this.At != 0)
                writer.writeInt64(5, this.At);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PC {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PC();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.ID = reader.readBytes();
                        break;
                    case 2:
                        message.UserID = reader.readBytes();
                        break;
                    case 3:
                        message.WorldID = reader.readBytes();
                        break;
                    case 4:
                        message.EntityID = reader.readBytes();
                        break;
                    case 5:
                        message.At = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PC {
            return PC.deserialize(bytes);
        }
    }
}
