// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/elojah/game_03/cmd/auth/grpc/auth.proto

package grpc

import (
	context "context"
	fmt "fmt"
	dto "github.com/elojah/game_03/pkg/user/dto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("github.com/elojah/game_03/cmd/auth/grpc/auth.proto", fileDescriptor_d94f16348cd64e2c)
}
func init() {
	golang_proto.RegisterFile("github.com/elojah/game_03/cmd/auth/grpc/auth.proto", fileDescriptor_d94f16348cd64e2c)
}

var fileDescriptor_d94f16348cd64e2c = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8f, 0xb1, 0x4e, 0xeb, 0x30,
	0x14, 0x86, 0x7d, 0xa4, 0xea, 0x0e, 0xd1, 0x95, 0x90, 0x32, 0x30, 0x04, 0x74, 0xde, 0x00, 0x1b,
	0x5a, 0x89, 0x8d, 0x01, 0x24, 0x04, 0x23, 0xa2, 0x88, 0x15, 0xa5, 0xa9, 0x71, 0x0c, 0x4d, 0x6c,
	0xb9, 0xb6, 0x2a, 0x36, 0x1e, 0x81, 0xc7, 0xe0, 0x11, 0x18, 0x18, 0x3a, 0x76, 0xcc, 0xd8, 0x91,
	0x38, 0x0b, 0x63, 0x47, 0x46, 0x54, 0xa7, 0xa8, 0x08, 0xd4, 0x81, 0xed, 0x3f, 0xe7, 0xf3, 0xe7,
	0xdf, 0x8e, 0xba, 0x42, 0xda, 0xdc, 0x0d, 0x68, 0xa6, 0x0a, 0xc6, 0x47, 0xea, 0x2e, 0xcd, 0x99,
	0x48, 0x0b, 0x7e, 0xb3, 0xdf, 0x63, 0x59, 0x31, 0x64, 0xa9, 0xb3, 0x39, 0x13, 0x46, 0x67, 0x21,
	0x51, 0x6d, 0x94, 0x55, 0x71, 0x67, 0xb9, 0x48, 0xf6, 0xbe, 0x99, 0x42, 0x09, 0xc5, 0x02, 0x1c,
	0xb8, 0xdb, 0x30, 0x85, 0x21, 0xa4, 0x56, 0x4a, 0x76, 0x84, 0x52, 0x62, 0xc4, 0xd7, 0xa7, 0x78,
	0xa1, 0xed, 0xc3, 0x0a, 0xe2, 0x4f, 0x38, 0x31, 0xa9, 0xd6, 0xdc, 0x8c, 0x57, 0xfc, 0x60, 0xf3,
	0x2b, 0xf5, 0xbd, 0x60, 0x6e, 0xcc, 0x0d, 0x1b, 0x5a, 0x15, 0x42, 0xab, 0x74, 0x5f, 0x21, 0xea,
	0x1c, 0x3b, 0x9b, 0xc7, 0x47, 0xd1, 0xff, 0xbe, 0x14, 0xa5, 0x2c, 0xaf, 0x26, 0xd2, 0x66, 0x79,
	0xbc, 0x4b, 0xdb, 0x32, 0xfa, 0x55, 0x46, 0xfb, 0xd6, 0xc8, 0x52, 0x5c, 0xa7, 0x23, 0xc7, 0x93,
	0x2d, 0x3a, 0xb4, 0x8a, 0xb6, 0xc2, 0x25, 0x1f, 0xeb, 0xb5, 0x7e, 0x16, 0xac, 0xbf, 0xea, 0x87,
	0x51, 0xe7, 0x42, 0x96, 0x22, 0xde, 0xfe, 0xa5, 0x9d, 0x2e, 0xff, 0x9f, 0x6c, 0xd8, 0x9f, 0x9c,
	0xcf, 0x6a, 0x24, 0x55, 0x8d, 0x64, 0x5e, 0x23, 0x59, 0xd4, 0x08, 0x1f, 0x35, 0xc2, 0xa3, 0x47,
	0x78, 0xf6, 0x08, 0x2f, 0x1e, 0x61, 0xea, 0x11, 0x66, 0x1e, 0xa1, 0xf2, 0x08, 0x6f, 0x1e, 0xe1,
	0xdd, 0x23, 0x59, 0x78, 0x84, 0xa7, 0x06, 0xc9, 0xb4, 0x41, 0xa8, 0x1a, 0x24, 0xf3, 0x06, 0xc9,
	0xe0, 0x5f, 0xb8, 0xb9, 0xf7, 0x19, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x81, 0xc8, 0xa7, 0xea, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Signin Twitch
	SigninTwitch(ctx context.Context, in *types.StringValue, opts ...grpc.CallOption) (*dto.SigninResp, error)
	// Signin Google
	SigninGoogle(ctx context.Context, in *types.StringValue, opts ...grpc.CallOption) (*dto.SigninResp, error)
	// Ping
	Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SigninTwitch(ctx context.Context, in *types.StringValue, opts ...grpc.CallOption) (*dto.SigninResp, error) {
	out := new(dto.SigninResp)
	err := c.cc.Invoke(ctx, "/grpc.Auth/SigninTwitch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SigninGoogle(ctx context.Context, in *types.StringValue, opts ...grpc.CallOption) (*dto.SigninResp, error) {
	out := new(dto.SigninResp)
	err := c.cc.Invoke(ctx, "/grpc.Auth/SigninGoogle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/grpc.Auth/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Signin Twitch
	SigninTwitch(context.Context, *types.StringValue) (*dto.SigninResp, error)
	// Signin Google
	SigninGoogle(context.Context, *types.StringValue) (*dto.SigninResp, error)
	// Ping
	Ping(context.Context, *types.Empty) (*types.Empty, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) SigninTwitch(ctx context.Context, req *types.StringValue) (*dto.SigninResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigninTwitch not implemented")
}
func (*UnimplementedAuthServer) SigninGoogle(ctx context.Context, req *types.StringValue) (*dto.SigninResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SigninGoogle not implemented")
}
func (*UnimplementedAuthServer) Ping(ctx context.Context, req *types.Empty) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SigninTwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SigninTwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/SigninTwitch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SigninTwitch(ctx, req.(*types.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SigninGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SigninGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/SigninGoogle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SigninGoogle(ctx, req.(*types.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Auth/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Ping(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SigninTwitch",
			Handler:    _Auth_SigninTwitch_Handler,
		},
		{
			MethodName: "SigninGoogle",
			Handler:    _Auth_SigninGoogle_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Auth_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/elojah/game_03/cmd/auth/grpc/auth.proto",
}
