/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: github.com/elojah/game_03/cmd/auth/grpc/auth.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../../../gogo/protobuf/gogoproto/gogo";
import * as dependency_2 from "./../../../../../../google/protobuf/empty";
import * as dependency_3 from "./../../../../../../google/protobuf/wrappers";
import * as dependency_4 from "./../../../pkg/user/dto/user";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace grpc {
    export class _ extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): _ {
            const message = new _({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): _ {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new _();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): _ {
            return _.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedAuthService {
        static definition = {
            SigninTwitch: {
                path: "/grpc.Auth/SigninTwitch",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.google.protobuf.StringValue) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.google.protobuf.StringValue.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.dto.SigninResp) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.dto.SigninResp.deserialize(new Uint8Array(bytes))
            },
            SigninGoogle: {
                path: "/grpc.Auth/SigninGoogle",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.google.protobuf.StringValue) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.google.protobuf.StringValue.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.dto.SigninResp) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.dto.SigninResp.deserialize(new Uint8Array(bytes))
            },
            RefreshToken: {
                path: "/grpc.Auth/RefreshToken",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_3.google.protobuf.StringValue) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_3.google.protobuf.StringValue.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_4.dto.SigninResp) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_4.dto.SigninResp.deserialize(new Uint8Array(bytes))
            },
            Ping: {
                path: "/grpc.Auth/Ping",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_2.google.protobuf.Empty) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_2.google.protobuf.Empty.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract SigninTwitch(call: grpc_1.ServerUnaryCall<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp>, callback: grpc_1.sendUnaryData<dependency_4.dto.SigninResp>): void;
        abstract SigninGoogle(call: grpc_1.ServerUnaryCall<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp>, callback: grpc_1.sendUnaryData<dependency_4.dto.SigninResp>): void;
        abstract RefreshToken(call: grpc_1.ServerUnaryCall<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp>, callback: grpc_1.sendUnaryData<dependency_4.dto.SigninResp>): void;
        abstract Ping(call: grpc_1.ServerUnaryCall<dependency_2.google.protobuf.Empty, dependency_2.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_2.google.protobuf.Empty>): void;
    }
    export class AuthClient extends grpc_1.makeGenericClientConstructor(UnimplementedAuthService.definition, "Auth", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        SigninTwitch: GrpcUnaryServiceInterface<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp> = (message: dependency_3.google.protobuf.StringValue, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, callback?: grpc_1.requestCallback<dependency_4.dto.SigninResp>): grpc_1.ClientUnaryCall => {
            return super.SigninTwitch(message, metadata, options, callback);
        };
        SigninGoogle: GrpcUnaryServiceInterface<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp> = (message: dependency_3.google.protobuf.StringValue, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, callback?: grpc_1.requestCallback<dependency_4.dto.SigninResp>): grpc_1.ClientUnaryCall => {
            return super.SigninGoogle(message, metadata, options, callback);
        };
        RefreshToken: GrpcUnaryServiceInterface<dependency_3.google.protobuf.StringValue, dependency_4.dto.SigninResp> = (message: dependency_3.google.protobuf.StringValue, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_4.dto.SigninResp>, callback?: grpc_1.requestCallback<dependency_4.dto.SigninResp>): grpc_1.ClientUnaryCall => {
            return super.RefreshToken(message, metadata, options, callback);
        };
        Ping: GrpcUnaryServiceInterface<dependency_2.google.protobuf.Empty, dependency_2.google.protobuf.Empty> = (message: dependency_2.google.protobuf.Empty, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_2.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.Ping(message, metadata, options, callback);
        };
    }
}
