// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/elojah/game_03/pkg/entity/dto/pc.proto

package dto

import (
	bytes "bytes"
	fmt "fmt"
	entity "github.com/elojah/game_03/pkg/entity"
	github_com_elojah_game_03_pkg_ulid "github.com/elojah/game_03/pkg/ulid"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PC struct {
	entity.PC `protobuf:"bytes,1,opt,name=PC,proto3,embedded=PC" json:"PC"`
	Entity    entity.E `protobuf:"bytes,2,opt,name=Entity,proto3" json:"Entity"`
}

func (m *PC) Reset()      { *m = PC{} }
func (*PC) ProtoMessage() {}
func (*PC) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3acf6b9c23e297b, []int{0}
}
func (m *PC) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PC.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PC.Merge(m, src)
}
func (m *PC) XXX_Size() int {
	return m.Size()
}
func (m *PC) XXX_DiscardUnknown() {
	xxx_messageInfo_PC.DiscardUnknown(m)
}

var xxx_messageInfo_PC proto.InternalMessageInfo

type CreatePCReq struct {
	RoomID         github_com_elojah_game_03_pkg_ulid.ID `protobuf:"bytes,1,opt,name=RoomID,proto3,customtype=github.com/elojah/game_03/pkg/ulid.ID" json:"RoomID"`
	EntityTemplate string                                `protobuf:"bytes,2,opt,name=EntityTemplate,proto3" json:"EntityTemplate,omitempty"`
}

func (m *CreatePCReq) Reset()      { *m = CreatePCReq{} }
func (*CreatePCReq) ProtoMessage() {}
func (*CreatePCReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3acf6b9c23e297b, []int{1}
}
func (m *CreatePCReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePCReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePCReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePCReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePCReq.Merge(m, src)
}
func (m *CreatePCReq) XXX_Size() int {
	return m.Size()
}
func (m *CreatePCReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePCReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePCReq proto.InternalMessageInfo

type ListPCReq struct {
	RoomID github_com_elojah_game_03_pkg_ulid.ID `protobuf:"bytes,1,opt,name=RoomID,proto3,customtype=github.com/elojah/game_03/pkg/ulid.ID" json:"RoomID"`
	Size_  int64                                 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	State  []byte                                `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`
}

func (m *ListPCReq) Reset()      { *m = ListPCReq{} }
func (*ListPCReq) ProtoMessage() {}
func (*ListPCReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3acf6b9c23e297b, []int{2}
}
func (m *ListPCReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPCReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListPCReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListPCReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPCReq.Merge(m, src)
}
func (m *ListPCReq) XXX_Size() int {
	return m.Size()
}
func (m *ListPCReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPCReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPCReq proto.InternalMessageInfo

type ListPCResp struct {
	PCs   []PC   `protobuf:"bytes,1,rep,name=PCs,proto3" json:"PCs"`
	State []byte `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
}

func (m *ListPCResp) Reset()      { *m = ListPCResp{} }
func (*ListPCResp) ProtoMessage() {}
func (*ListPCResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3acf6b9c23e297b, []int{3}
}
func (m *ListPCResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPCResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListPCResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListPCResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPCResp.Merge(m, src)
}
func (m *ListPCResp) XXX_Size() int {
	return m.Size()
}
func (m *ListPCResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPCResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListPCResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PC)(nil), "dto.PC")
	golang_proto.RegisterType((*PC)(nil), "dto.PC")
	proto.RegisterType((*CreatePCReq)(nil), "dto.CreatePCReq")
	golang_proto.RegisterType((*CreatePCReq)(nil), "dto.CreatePCReq")
	proto.RegisterType((*ListPCReq)(nil), "dto.ListPCReq")
	golang_proto.RegisterType((*ListPCReq)(nil), "dto.ListPCReq")
	proto.RegisterType((*ListPCResp)(nil), "dto.ListPCResp")
	golang_proto.RegisterType((*ListPCResp)(nil), "dto.ListPCResp")
}

func init() {
	proto.RegisterFile("github.com/elojah/game_03/pkg/entity/dto/pc.proto", fileDescriptor_b3acf6b9c23e297b)
}
func init() {
	golang_proto.RegisterFile("github.com/elojah/game_03/pkg/entity/dto/pc.proto", fileDescriptor_b3acf6b9c23e297b)
}

var fileDescriptor_b3acf6b9c23e297b = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0x3d, 0xef, 0xd2, 0x40,
	0x18, 0xbf, 0xa3, 0x88, 0x72, 0x18, 0x87, 0xc6, 0x81, 0x30, 0x3c, 0x25, 0x8d, 0x2f, 0x2c, 0xb4,
	0x0a, 0xdf, 0xa0, 0x85, 0x44, 0x12, 0x87, 0xe6, 0x70, 0x37, 0x85, 0x9e, 0xa5, 0x4a, 0xbd, 0x0a,
	0xc7, 0xa0, 0x61, 0xf0, 0x23, 0xf8, 0x31, 0xfc, 0x08, 0x8e, 0x8c, 0x8c, 0x1d, 0x89, 0x03, 0xb1,
	0xd7, 0xc5, 0x91, 0xd1, 0xd1, 0xdc, 0x15, 0x22, 0x9a, 0x68, 0x1c, 0xfe, 0x4b, 0xfb, 0x3c, 0xfd,
	0xbd, 0xe6, 0x29, 0x79, 0x1a, 0x27, 0x62, 0xb1, 0x99, 0x39, 0x73, 0x9e, 0xba, 0x6c, 0xc9, 0x5f,
	0x87, 0x0b, 0x37, 0x0e, 0x53, 0xf6, 0xf2, 0xc9, 0xd0, 0xcd, 0xde, 0xc4, 0x2e, 0x7b, 0x2b, 0x12,
	0xf1, 0xde, 0x8d, 0x04, 0x77, 0xb3, 0xb9, 0x93, 0xad, 0xb8, 0xe0, 0xa6, 0x11, 0x09, 0xde, 0xe9,
	0x5f, 0xe9, 0x62, 0x1e, 0x73, 0x57, 0x63, 0xb3, 0xcd, 0x2b, 0xbd, 0xe9, 0x45, 0x4f, 0x95, 0xe6,
	0x37, 0xfa, 0xdf, 0x63, 0x2e, 0x11, 0x9d, 0xff, 0x6b, 0x55, 0xbd, 0x2a, 0x89, 0x3d, 0x25, 0xb5,
	0xc0, 0x37, 0x1f, 0xa8, 0x67, 0x1b, 0x77, 0x71, 0xaf, 0x35, 0x20, 0xce, 0x99, 0x10, 0xf8, 0xde,
	0x9d, 0xfd, 0xd1, 0x42, 0xf9, 0xd1, 0xc2, 0x54, 0xb1, 0x1e, 0x93, 0xc6, 0x58, 0x43, 0xed, 0x9a,
	0x66, 0x36, 0x2f, 0xcc, 0xb1, 0x57, 0x57, 0x44, 0x7a, 0x86, 0xed, 0x2d, 0x69, 0xf9, 0x2b, 0x16,
	0x0a, 0x16, 0xf8, 0x94, 0xbd, 0x33, 0xc7, 0xa4, 0x41, 0x39, 0x4f, 0x27, 0x23, 0x9d, 0x70, 0xd7,
	0xeb, 0x2b, 0xf2, 0xd7, 0xa3, 0xf5, 0xf0, 0xdf, 0x75, 0x37, 0xcb, 0x24, 0x72, 0x26, 0x23, 0x7a,
	0x16, 0x9b, 0x8f, 0xc8, 0xbd, 0xca, 0xff, 0x05, 0x4b, 0xb3, 0x65, 0x28, 0x98, 0xae, 0xd1, 0xa4,
	0x7f, 0x7c, 0xb5, 0xb7, 0xa4, 0xf9, 0x3c, 0x59, 0x8b, 0x1b, 0xcd, 0x36, 0x49, 0x7d, 0x9a, 0x7c,
	0xa8, 0x12, 0x0d, 0xaa, 0x67, 0xf3, 0x3e, 0xb9, 0x35, 0x15, 0xaa, 0x86, 0xa1, 0x9c, 0x69, 0xb5,
	0xd8, 0x3e, 0x21, 0x97, 0xf4, 0x75, 0x66, 0x5a, 0xc4, 0x08, 0xfc, 0x75, 0x1b, 0x77, 0x8d, 0x5e,
	0x6b, 0x70, 0xdb, 0x89, 0x04, 0x57, 0x67, 0xad, 0xae, 0xa5, 0x90, 0x5f, 0x26, 0xb5, 0x2b, 0x13,
	0xef, 0xd9, 0xbe, 0x00, 0x94, 0x17, 0x80, 0x0e, 0x05, 0xa0, 0x53, 0x01, 0xf8, 0x47, 0x01, 0xf8,
	0xa3, 0x04, 0xfc, 0x59, 0x02, 0xfe, 0x22, 0x01, 0xef, 0x24, 0xe0, 0xbd, 0x04, 0x9c, 0x4b, 0xc0,
	0xdf, 0x24, 0xe0, 0xef, 0x12, 0xd0, 0x49, 0x02, 0xfe, 0x54, 0x02, 0xda, 0x95, 0x80, 0xf3, 0x12,
	0xd0, 0xa1, 0x04, 0x34, 0x6b, 0xe8, 0xdf, 0x3c, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x77,
	0x72, 0x5c, 0xb1, 0x02, 0x00, 0x00,
}

func (this *PC) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PC)
	if !ok {
		that2, ok := that.(PC)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PC.Equal(&that1.PC) {
		return false
	}
	if !this.Entity.Equal(&that1.Entity) {
		return false
	}
	return true
}
func (this *CreatePCReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CreatePCReq)
	if !ok {
		that2, ok := that.(CreatePCReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RoomID.Equal(that1.RoomID) {
		return false
	}
	if this.EntityTemplate != that1.EntityTemplate {
		return false
	}
	return true
}
func (this *ListPCReq) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListPCReq)
	if !ok {
		that2, ok := that.(ListPCReq)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.RoomID.Equal(that1.RoomID) {
		return false
	}
	if this.Size_ != that1.Size_ {
		return false
	}
	if !bytes.Equal(this.State, that1.State) {
		return false
	}
	return true
}
func (this *ListPCResp) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ListPCResp)
	if !ok {
		that2, ok := that.(ListPCResp)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.PCs) != len(that1.PCs) {
		return false
	}
	for i := range this.PCs {
		if !this.PCs[i].Equal(&that1.PCs[i]) {
			return false
		}
	}
	if !bytes.Equal(this.State, that1.State) {
		return false
	}
	return true
}
func (this *PC) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dto.PC{")
	s = append(s, "PC: "+strings.Replace(this.PC.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "Entity: "+strings.Replace(this.Entity.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CreatePCReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dto.CreatePCReq{")
	s = append(s, "RoomID: "+fmt.Sprintf("%#v", this.RoomID)+",\n")
	s = append(s, "EntityTemplate: "+fmt.Sprintf("%#v", this.EntityTemplate)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListPCReq) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&dto.ListPCReq{")
	s = append(s, "RoomID: "+fmt.Sprintf("%#v", this.RoomID)+",\n")
	s = append(s, "Size_: "+fmt.Sprintf("%#v", this.Size_)+",\n")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ListPCResp) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&dto.ListPCResp{")
	if this.PCs != nil {
		vs := make([]PC, len(this.PCs))
		for i := range vs {
			vs[i] = this.PCs[i]
		}
		s = append(s, "PCs: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringPc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *PC) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PC) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PC) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Entity.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.PC.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *CreatePCReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePCReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePCReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EntityTemplate) > 0 {
		i -= len(m.EntityTemplate)
		copy(dAtA[i:], m.EntityTemplate)
		i = encodeVarintPc(dAtA, i, uint64(len(m.EntityTemplate)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.RoomID.Size()
		i -= size
		if _, err := m.RoomID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ListPCReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPCReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPCReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintPc(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Size_ != 0 {
		i = encodeVarintPc(dAtA, i, uint64(m.Size_))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.RoomID.Size()
		i -= size
		if _, err := m.RoomID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ListPCResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPCResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPCResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintPc(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PCs) > 0 {
		for iNdEx := len(m.PCs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PCs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintPc(dAtA []byte, offset int, v uint64) int {
	offset -= sovPc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedPC(r randyPc, easy bool) *PC {
	this := &PC{}
	v1 := entity.NewPopulatedPC(r, easy)
	this.PC = *v1
	v2 := entity.NewPopulatedE(r, easy)
	this.Entity = *v2
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedCreatePCReq(r randyPc, easy bool) *CreatePCReq {
	this := &CreatePCReq{}
	v3 := github_com_elojah_game_03_pkg_ulid.NewPopulatedID(r)
	this.RoomID = *v3
	this.EntityTemplate = string(randStringPc(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedListPCReq(r randyPc, easy bool) *ListPCReq {
	this := &ListPCReq{}
	v4 := github_com_elojah_game_03_pkg_ulid.NewPopulatedID(r)
	this.RoomID = *v4
	this.Size_ = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Size_ *= -1
	}
	v5 := r.Intn(100)
	this.State = make([]byte, v5)
	for i := 0; i < v5; i++ {
		this.State[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedListPCResp(r randyPc, easy bool) *ListPCResp {
	this := &ListPCResp{}
	if r.Intn(5) != 0 {
		v6 := r.Intn(5)
		this.PCs = make([]PC, v6)
		for i := 0; i < v6; i++ {
			v7 := NewPopulatedPC(r, easy)
			this.PCs[i] = *v7
		}
	}
	v8 := r.Intn(100)
	this.State = make([]byte, v8)
	for i := 0; i < v8; i++ {
		this.State[i] = byte(r.Intn(256))
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyPc interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RunePc(r randyPc) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringPc(r randyPc) string {
	v9 := r.Intn(100)
	tmps := make([]rune, v9)
	for i := 0; i < v9; i++ {
		tmps[i] = randUTF8RunePc(r)
	}
	return string(tmps)
}
func randUnrecognizedPc(r randyPc, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldPc(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldPc(dAtA []byte, r randyPc, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulatePc(dAtA, uint64(key))
		v10 := r.Int63()
		if r.Intn(2) == 0 {
			v10 *= -1
		}
		dAtA = encodeVarintPopulatePc(dAtA, uint64(v10))
	case 1:
		dAtA = encodeVarintPopulatePc(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulatePc(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulatePc(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulatePc(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulatePc(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *PC) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PC.Size()
	n += 1 + l + sovPc(uint64(l))
	l = m.Entity.Size()
	n += 1 + l + sovPc(uint64(l))
	return n
}

func (m *CreatePCReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RoomID.Size()
	n += 1 + l + sovPc(uint64(l))
	l = len(m.EntityTemplate)
	if l > 0 {
		n += 1 + l + sovPc(uint64(l))
	}
	return n
}

func (m *ListPCReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RoomID.Size()
	n += 1 + l + sovPc(uint64(l))
	if m.Size_ != 0 {
		n += 1 + sovPc(uint64(m.Size_))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovPc(uint64(l))
	}
	return n
}

func (m *ListPCResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PCs) > 0 {
		for _, e := range m.PCs {
			l = e.Size()
			n += 1 + l + sovPc(uint64(l))
		}
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovPc(uint64(l))
	}
	return n
}

func sovPc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPc(x uint64) (n int) {
	return sovPc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *PC) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PC{`,
		`PC:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PC), "PC", "entity.PC", 1), `&`, ``, 1) + `,`,
		`Entity:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Entity), "E", "entity.E", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CreatePCReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CreatePCReq{`,
		`RoomID:` + fmt.Sprintf("%v", this.RoomID) + `,`,
		`EntityTemplate:` + fmt.Sprintf("%v", this.EntityTemplate) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListPCReq) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListPCReq{`,
		`RoomID:` + fmt.Sprintf("%v", this.RoomID) + `,`,
		`Size_:` + fmt.Sprintf("%v", this.Size_) + `,`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListPCResp) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForPCs := "[]PC{"
	for _, f := range this.PCs {
		repeatedStringForPCs += strings.Replace(strings.Replace(f.String(), "PC", "PC", 1), `&`, ``, 1) + ","
	}
	repeatedStringForPCs += "}"
	s := strings.Join([]string{`&ListPCResp{`,
		`PCs:` + repeatedStringForPCs + `,`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringPc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *PC) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PC: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PC: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PC", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PC.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entity", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Entity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePCReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePCReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePCReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoomID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntityTemplate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntityTemplate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPCReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPCReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPCReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoomID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			m.Size_ = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Size_ |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = append(m.State[:0], dAtA[iNdEx:postIndex]...)
			if m.State == nil {
				m.State = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPCResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPCResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPCResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PCs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PCs = append(m.PCs, PC{})
			if err := m.PCs[len(m.PCs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = append(m.State[:0], dAtA[iNdEx:postIndex]...)
			if m.State == nil {
				m.State = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPc = fmt.Errorf("proto: unexpected end of group")
)
