// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/elojah/game_03/pkg/space/entity.proto

package space

import (
	fmt "fmt"
	github_com_elojah_game_03_pkg_ulid "github.com/elojah/game_03/pkg/ulid"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Cross int32

const (
	In  Cross = 0
	Out Cross = 1
)

var Cross_name = map[int32]string{
	0: "In",
	1: "Out",
}

var Cross_value = map[string]int32{
	"In":  0,
	"Out": 1,
}

func (Cross) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4616edb3a77b3c31, []int{0}
}

type Entity struct {
	ID      github_com_elojah_game_03_pkg_ulid.ID `protobuf:"bytes,1,opt,name=ID,proto3,customtype=github.com/elojah/game_03/pkg/ulid.ID" json:"ID"`
	Section Section                               `protobuf:"bytes,2,opt,name=Section,proto3" json:"Section"`
	Cross   Cross                                 `protobuf:"varint,3,opt,name=Cross,proto3,enum=space.Cross" json:"Cross,omitempty"`
	State   github_com_elojah_game_03_pkg_ulid.ID `protobuf:"bytes,4,opt,name=State,proto3,customtype=github.com/elojah/game_03/pkg/ulid.ID" json:"State"`
}

func (m *Entity) Reset()      { *m = Entity{} }
func (*Entity) ProtoMessage() {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4616edb3a77b3c31, []int{0}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return m.Size()
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetSection() Section {
	if m != nil {
		return m.Section
	}
	return Section{}
}

func (m *Entity) GetCross() Cross {
	if m != nil {
		return m.Cross
	}
	return In
}

func init() {
	proto.RegisterEnum("space.Cross", Cross_name, Cross_value)
	golang_proto.RegisterEnum("space.Cross", Cross_name, Cross_value)
	proto.RegisterType((*Entity)(nil), "space.Entity")
	golang_proto.RegisterType((*Entity)(nil), "space.Entity")
}

func init() {
	proto.RegisterFile("github.com/elojah/game_03/pkg/space/entity.proto", fileDescriptor_4616edb3a77b3c31)
}
func init() {
	golang_proto.RegisterFile("github.com/elojah/game_03/pkg/space/entity.proto", fileDescriptor_4616edb3a77b3c31)
}

var fileDescriptor_4616edb3a77b3c31 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xbf, 0x6a, 0x02, 0x41,
	0x10, 0x87, 0x77, 0xce, 0x7f, 0xb0, 0x11, 0x91, 0xad, 0x0e, 0x8b, 0x51, 0x84, 0x80, 0x04, 0xbc,
	0x15, 0xad, 0xd3, 0xe8, 0xa5, 0xb8, 0x2a, 0xa0, 0x0f, 0x10, 0x4e, 0xdd, 0x9c, 0x97, 0xa8, 0x2b,
	0xba, 0x47, 0x48, 0x97, 0x47, 0xc8, 0x63, 0xe4, 0x11, 0x52, 0x5a, 0x5a, 0x5a, 0x4a, 0x0a, 0xf1,
	0xf6, 0x9a, 0x94, 0x96, 0x29, 0x43, 0xf6, 0x0c, 0xa4, 0x0a, 0x21, 0xdd, 0xce, 0x6f, 0xe6, 0x9b,
	0x6f, 0x19, 0xda, 0x0a, 0x42, 0x35, 0x89, 0x86, 0xce, 0x48, 0xce, 0xb8, 0x98, 0xca, 0x3b, 0x7f,
	0xc2, 0x03, 0x7f, 0x26, 0x6e, 0x5a, 0x1d, 0xbe, 0xb8, 0x0f, 0xf8, 0x6a, 0xe1, 0x8f, 0x04, 0x17,
	0x73, 0x15, 0xaa, 0x47, 0x67, 0xb1, 0x94, 0x4a, 0xb2, 0x9c, 0xc9, 0x2a, 0xcd, 0x1f, 0x60, 0x20,
	0x03, 0xc9, 0x4d, 0x77, 0x18, 0xdd, 0x9a, 0xca, 0x14, 0xe6, 0x95, 0x52, 0x15, 0xfe, 0x17, 0xcf,
	0x83, 0x5c, 0x4e, 0xc7, 0x29, 0x50, 0x3f, 0x00, 0xcd, 0x5f, 0x19, 0x2f, 0xbb, 0xa4, 0x96, 0xe7,
	0xda, 0x50, 0x83, 0x46, 0xb1, 0xdb, 0xdc, 0xec, 0xab, 0xe4, 0x6d, 0x5f, 0x3d, 0xff, 0x7d, 0x5f,
	0x34, 0x0d, 0xc7, 0x8e, 0xe7, 0xf6, 0x2d, 0xcf, 0x65, 0x0e, 0x2d, 0x0c, 0xc4, 0x48, 0x85, 0x72,
	0x6e, 0x5b, 0x35, 0x68, 0x9c, 0xb5, 0x4b, 0x8e, 0xd1, 0x39, 0xa7, 0xb4, 0x9b, 0xfd, 0xda, 0xd9,
	0xff, 0x1e, 0x62, 0x75, 0x9a, 0xeb, 0x2d, 0xe5, 0x6a, 0x65, 0x67, 0x6a, 0xd0, 0x28, 0xb5, 0x8b,
	0xa7, 0x69, 0x93, 0xf5, 0xd3, 0x16, 0xeb, 0xd1, 0xdc, 0x40, 0xf9, 0x4a, 0xd8, 0xd9, 0xff, 0xfc,
	0x2a, 0x65, 0x2f, 0xec, 0x93, 0x88, 0xe5, 0xa9, 0xe5, 0xcd, 0xcb, 0x84, 0x15, 0x68, 0xe6, 0x3a,
	0x52, 0x65, 0xe8, 0xba, 0xdb, 0x18, 0xc9, 0x2e, 0x46, 0x72, 0x8c, 0x11, 0x3e, 0x62, 0x84, 0x27,
	0x8d, 0xf0, 0xa2, 0x11, 0x5e, 0x35, 0xc2, 0x5a, 0x23, 0x6c, 0x34, 0xc2, 0x56, 0x23, 0x1c, 0x34,
	0xc2, 0xbb, 0x46, 0x72, 0xd4, 0x08, 0xcf, 0x09, 0x92, 0x75, 0x82, 0xb0, 0x4d, 0x90, 0xec, 0x12,
	0x24, 0xc3, 0xbc, 0xb9, 0x64, 0xe7, 0x33, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xc7, 0x92, 0x99, 0xe4,
	0x01, 0x00, 0x00,
}

func (x Cross) String() string {
	s, ok := Cross_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Entity) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Entity)
	if !ok {
		that2, ok := that.(Entity)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.ID.Equal(that1.ID) {
		return false
	}
	if !this.Section.Equal(&that1.Section) {
		return false
	}
	if this.Cross != that1.Cross {
		return false
	}
	if !this.State.Equal(that1.State) {
		return false
	}
	return true
}
func (this *Entity) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&space.Entity{")
	s = append(s, "ID: "+fmt.Sprintf("%#v", this.ID)+",\n")
	s = append(s, "Section: "+strings.Replace(this.Section.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "Cross: "+fmt.Sprintf("%#v", this.Cross)+",\n")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringEntity(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Entity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Entity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Entity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.State.Size()
		i -= size
		if _, err := m.State.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEntity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Cross != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.Cross))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Section.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEntity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEntity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEntity(dAtA []byte, offset int, v uint64) int {
	offset -= sovEntity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedEntity(r randyEntity, easy bool) *Entity {
	this := &Entity{}
	v1 := github_com_elojah_game_03_pkg_ulid.NewPopulatedID(r)
	this.ID = *v1
	v2 := NewPopulatedSection(r, easy)
	this.Section = *v2
	this.Cross = Cross([]int32{0, 1}[r.Intn(2)])
	v3 := github_com_elojah_game_03_pkg_ulid.NewPopulatedID(r)
	this.State = *v3
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

type randyEntity interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneEntity(r randyEntity) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringEntity(r randyEntity) string {
	v4 := r.Intn(100)
	tmps := make([]rune, v4)
	for i := 0; i < v4; i++ {
		tmps[i] = randUTF8RuneEntity(r)
	}
	return string(tmps)
}
func randUnrecognizedEntity(r randyEntity, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldEntity(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldEntity(dAtA []byte, r randyEntity, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		v5 := r.Int63()
		if r.Intn(2) == 0 {
			v5 *= -1
		}
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(v5))
	case 1:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateEntity(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateEntity(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Entity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovEntity(uint64(l))
	l = m.Section.Size()
	n += 1 + l + sovEntity(uint64(l))
	if m.Cross != 0 {
		n += 1 + sovEntity(uint64(m.Cross))
	}
	l = m.State.Size()
	n += 1 + l + sovEntity(uint64(l))
	return n
}

func sovEntity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEntity(x uint64) (n int) {
	return sovEntity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Entity) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Entity{`,
		`ID:` + fmt.Sprintf("%v", this.ID) + `,`,
		`Section:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Section), "Section", "Section", 1), `&`, ``, 1) + `,`,
		`Cross:` + fmt.Sprintf("%v", this.Cross) + `,`,
		`State:` + fmt.Sprintf("%v", this.State) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringEntity(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Entity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Entity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Entity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Section", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Section.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cross", wireType)
			}
			m.Cross = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cross |= Cross(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEntity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEntity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEntity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEntity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEntity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEntity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEntity = fmt.Errorf("proto: unexpected end of group")
)
