/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: github.com/elojah/game_03/pkg/room/room.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../../gogo/protobuf/gogoproto/gogo";
import * as pb_1 from "google-protobuf";
export namespace room {
    export class R extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            ID?: Uint8Array;
            OwnerID?: Uint8Array;
            WorldID?: Uint8Array;
            Name?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("ID" in data && data.ID != undefined) {
                    this.ID = data.ID;
                }
                if ("OwnerID" in data && data.OwnerID != undefined) {
                    this.OwnerID = data.OwnerID;
                }
                if ("WorldID" in data && data.WorldID != undefined) {
                    this.WorldID = data.WorldID;
                }
                if ("Name" in data && data.Name != undefined) {
                    this.Name = data.Name;
                }
            }
        }
        get ID() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set ID(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get OwnerID() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set OwnerID(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get WorldID() {
            return pb_1.Message.getFieldWithDefault(this, 3, new Uint8Array(0)) as Uint8Array;
        }
        set WorldID(value: Uint8Array) {
            pb_1.Message.setField(this, 3, value);
        }
        get Name() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set Name(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            ID?: Uint8Array;
            OwnerID?: Uint8Array;
            WorldID?: Uint8Array;
            Name?: string;
        }): R {
            const message = new R({});
            if (data.ID != null) {
                message.ID = data.ID;
            }
            if (data.OwnerID != null) {
                message.OwnerID = data.OwnerID;
            }
            if (data.WorldID != null) {
                message.WorldID = data.WorldID;
            }
            if (data.Name != null) {
                message.Name = data.Name;
            }
            return message;
        }
        toObject() {
            const data: {
                ID?: Uint8Array;
                OwnerID?: Uint8Array;
                WorldID?: Uint8Array;
                Name?: string;
            } = {};
            if (this.ID != null) {
                data.ID = this.ID;
            }
            if (this.OwnerID != null) {
                data.OwnerID = this.OwnerID;
            }
            if (this.WorldID != null) {
                data.WorldID = this.WorldID;
            }
            if (this.Name != null) {
                data.Name = this.Name;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.ID.length)
                writer.writeBytes(1, this.ID);
            if (this.OwnerID.length)
                writer.writeBytes(2, this.OwnerID);
            if (this.WorldID.length)
                writer.writeBytes(3, this.WorldID);
            if (this.Name.length)
                writer.writeString(4, this.Name);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): R {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new R();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.ID = reader.readBytes();
                        break;
                    case 2:
                        message.OwnerID = reader.readBytes();
                        break;
                    case 3:
                        message.WorldID = reader.readBytes();
                        break;
                    case 4:
                        message.Name = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): R {
            return R.deserialize(bytes);
        }
    }
    export class Public extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            ID?: Uint8Array;
            RoomID?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("ID" in data && data.ID != undefined) {
                    this.ID = data.ID;
                }
                if ("RoomID" in data && data.RoomID != undefined) {
                    this.RoomID = data.RoomID;
                }
            }
        }
        get ID() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set ID(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get RoomID() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set RoomID(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            ID?: Uint8Array;
            RoomID?: Uint8Array;
        }): Public {
            const message = new Public({});
            if (data.ID != null) {
                message.ID = data.ID;
            }
            if (data.RoomID != null) {
                message.RoomID = data.RoomID;
            }
            return message;
        }
        toObject() {
            const data: {
                ID?: Uint8Array;
                RoomID?: Uint8Array;
            } = {};
            if (this.ID != null) {
                data.ID = this.ID;
            }
            if (this.RoomID != null) {
                data.RoomID = this.RoomID;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.ID.length)
                writer.writeBytes(1, this.ID);
            if (this.RoomID.length)
                writer.writeBytes(2, this.RoomID);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Public {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Public();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.ID = reader.readBytes();
                        break;
                    case 2:
                        message.RoomID = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Public {
            return Public.deserialize(bytes);
        }
    }
}
