#!/usr/bin/env bash

# Characters
cp -r ./assets/external/Characters/BlueNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMZ5HD82BSPTZ8YAAY.png   # BlueNinja
cp -r ./assets/external/Characters/BlueNinja/Faceset.png cmd/client/dist/img/assets/BlueNinja.png                        # BlueNinja
cp -r ./assets/external/Characters/BlueNinja/Faceset.png cmd/dashboard/dist/img/assets/BlueNinja.png                     # BlueNinja
cp -r ./assets/external/Characters/BlueSamurai/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMMR8ME1FM50A5BE8E.png # BlueSamurai
cp -r ./assets/external/Characters/BlueSamurai/Faceset.png cmd/client/dist/img/assets/BlueSamurai.png                    # BlueSamurai
cp -r ./assets/external/Characters/BlueSamurai/Faceset.png cmd/dashboard/dist/img/assets/BlueSamurai.png                 # BlueSamurai
cp -r ./assets/external/Characters/Boy/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMMYB38HS5X955K2HJ.png         # Boy
cp -r ./assets/external/Characters/Boy/Faceset.png cmd/client/dist/img/assets/Boy.png                                    # Boy
cp -r ./assets/external/Characters/Boy/Faceset.png cmd/dashboard/dist/img/assets/Boy.png                                 # Boy
cp -r ./assets/external/Characters/Cavegirl/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMSYJBMM38F8QMDZ41.png    # Cavegirl
cp -r ./assets/external/Characters/Cavegirl/Faceset.png cmd/client/dist/img/assets/Cavegirl.png                          # Cavegirl
cp -r ./assets/external/Characters/Cavegirl/Faceset.png cmd/dashboard/dist/img/assets/Cavegirl.png                       # Cavegirl
cp -r ./assets/external/Characters/Cavegirl2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM9QPEGNQ43HTE9RBP.png   # Cavegirl2
cp -r ./assets/external/Characters/Cavegirl2/Faceset.png cmd/client/dist/img/assets/Cavegirl2.png                        # Cavegirl2
cp -r ./assets/external/Characters/Cavegirl2/Faceset.png cmd/dashboard/dist/img/assets/Cavegirl2.png                     # Cavegirl2
cp -r ./assets/external/Characters/Caveman/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMA04AFK11TC5FHS5J.png     # Caveman
cp -r ./assets/external/Characters/Caveman/Faceset.png cmd/client/dist/img/assets/Caveman.png                            # Caveman
cp -r ./assets/external/Characters/Caveman/Faceset.png cmd/dashboard/dist/img/assets/Caveman.png                         # Caveman
cp -r ./assets/external/Characters/Caveman2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMTCHG0SEKPKWTRXQH.png    # Caveman2
cp -r ./assets/external/Characters/Caveman2/Faceset.png cmd/client/dist/img/assets/Caveman2.png                          # Caveman2
cp -r ./assets/external/Characters/Caveman2/Faceset.png cmd/dashboard/dist/img/assets/Caveman2.png                       # Caveman2
cp -r ./assets/external/Characters/Child/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMPP1NRHV2MFTWGCCA.png       # Child
cp -r ./assets/external/Characters/Child/Faceset.png cmd/client/dist/img/assets/Child.png                                # Child
cp -r ./assets/external/Characters/Child/Faceset.png cmd/dashboard/dist/img/assets/Child.png                             # Child
cp -r ./assets/external/Characters/DarkNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMX7RJRB5QD9H28M9K.png   # DarkNinja
cp -r ./assets/external/Characters/DarkNinja/Faceset.png cmd/client/dist/img/assets/DarkNinja.png                        # DarkNinja
cp -r ./assets/external/Characters/DarkNinja/Faceset.png cmd/dashboard/dist/img/assets/DarkNinja.png                     # DarkNinja
cp -r ./assets/external/Characters/EggBoy/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMDY74YT3TJSY9YWQE.png      # EggBoy
cp -r ./assets/external/Characters/EggBoy/Faceset.png cmd/client/dist/img/assets/EggBoy.png                              # EggBoy
cp -r ./assets/external/Characters/EggBoy/Faceset.png cmd/dashboard/dist/img/assets/EggBoy.png                           # EggBoy
cp -r ./assets/external/Characters/EggGirl/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMNRV1N8J1Q1X0QR1E.png     # EggGirl
cp -r ./assets/external/Characters/EggGirl/Faceset.png cmd/client/dist/img/assets/EggGirl.png                            # EggGirl
cp -r ./assets/external/Characters/EggGirl/Faceset.png cmd/dashboard/dist/img/assets/EggGirl.png                         # EggGirl
cp -r ./assets/external/Characters/Eskimo/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM7PH0DYGM4W6NNE3E.png      # Eskimo
cp -r ./assets/external/Characters/Eskimo/Faceset.png cmd/client/dist/img/assets/Eskimo.png                              # Eskimo
cp -r ./assets/external/Characters/Eskimo/Faceset.png cmd/dashboard/dist/img/assets/Eskimo.png                           # Eskimo
cp -r ./assets/external/Characters/EskimoNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMFZDHC84HH7WTF1ES.png # EskimoNinja
cp -r ./assets/external/Characters/EskimoNinja/Faceset.png cmd/client/dist/img/assets/EskimoNinja.png                    # EskimoNinja
cp -r ./assets/external/Characters/EskimoNinja/Faceset.png cmd/dashboard/dist/img/assets/EskimoNinja.png                 # EskimoNinja
cp -r ./assets/external/Characters/GoldKnight/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM83CP64RB0YKCR6AH.png  # GoldKnight
cp -r ./assets/external/Characters/GoldKnight/Faceset.png cmd/client/dist/img/assets/GoldKnight.png                      # GoldKnight
cp -r ./assets/external/Characters/GoldKnight/Faceset.png cmd/dashboard/dist/img/assets/GoldKnight.png                   # GoldKnight
cp -r ./assets/external/Characters/GrayNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMF8X4227SMB4F9HA6.png   # GrayNinja
cp -r ./assets/external/Characters/GrayNinja/Faceset.png cmd/client/dist/img/assets/GrayNinja.png                        # GrayNinja
cp -r ./assets/external/Characters/GrayNinja/Faceset.png cmd/dashboard/dist/img/assets/GrayNinja.png                     # GrayNinja
cp -r ./assets/external/Characters/Greenman/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMKY2Y398SNJ1XXB7Z.png    # Greenman
cp -r ./assets/external/Characters/Greenman/Faceset.png cmd/client/dist/img/assets/Greenman.png                          # Greenman
cp -r ./assets/external/Characters/Greenman/Faceset.png cmd/dashboard/dist/img/assets/Greenman.png                       # Greenman
cp -r ./assets/external/Characters/GreenNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMJWCBT1RNWKFXGDH8.png  # GreenNinja
cp -r ./assets/external/Characters/GreenNinja/Faceset.png cmd/client/dist/img/assets/GreenNinja.png                      # GreenNinja
cp -r ./assets/external/Characters/GreenNinja/Faceset.png cmd/dashboard/dist/img/assets/GreenNinja.png                   # GreenNinja
cp -r ./assets/external/Characters/Inspector/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM2977NCTE7WN2CGPZ.png   # Inspector
cp -r ./assets/external/Characters/Inspector/Faceset.png cmd/client/dist/img/assets/Inspector.png                        # Inspector
cp -r ./assets/external/Characters/Inspector/Faceset.png cmd/dashboard/dist/img/assets/Inspector.png                     # Inspector
cp -r ./assets/external/Characters/Knight/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMYC30729BW2DSTAAB.png      # Knight
cp -r ./assets/external/Characters/Knight/Faceset.png cmd/client/dist/img/assets/Knight.png                              # Knight
cp -r ./assets/external/Characters/Knight/Faceset.png cmd/dashboard/dist/img/assets/Knight.png                           # Knight
cp -r ./assets/external/Characters/Lion/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMJ16YDZXW5K6P8DD3.png        # Lion
cp -r ./assets/external/Characters/Lion/Faceset.png cmd/client/dist/img/assets/Lion.png                                  # Lion
cp -r ./assets/external/Characters/Lion/Faceset.png cmd/dashboard/dist/img/assets/Lion.png                               # Lion
cp -r ./assets/external/Characters/MaskedNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMX2N3MVESA3S42V4Q.png # MaskedNinja
cp -r ./assets/external/Characters/MaskedNinja/Faceset.png cmd/client/dist/img/assets/MaskedNinja.png                    # MaskedNinja
cp -r ./assets/external/Characters/MaskedNinja/Faceset.png cmd/dashboard/dist/img/assets/MaskedNinja.png                 # MaskedNinja
cp -r ./assets/external/Characters/MaskFrog/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMY486XKF297RF0VH0.png    # MaskFrog
cp -r ./assets/external/Characters/MaskFrog/Faceset.png cmd/client/dist/img/assets/MaskFrog.png                          # MaskFrog
cp -r ./assets/external/Characters/MaskFrog/Faceset.png cmd/dashboard/dist/img/assets/MaskFrog.png                       # MaskFrog
cp -r ./assets/external/Characters/Master/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMWKJ0Q56XMM8XFGX8.png      # Master
cp -r ./assets/external/Characters/Master/Faceset.png cmd/client/dist/img/assets/Master.png                              # Master
cp -r ./assets/external/Characters/Master/Faceset.png cmd/dashboard/dist/img/assets/Master.png                           # Master
cp -r ./assets/external/Characters/Monk/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMS4AZYZC1FG39FW61.png        # Monk
cp -r ./assets/external/Characters/Monk/Faceset.png cmd/client/dist/img/assets/Monk.png                                  # Monk
cp -r ./assets/external/Characters/Monk/Faceset.png cmd/dashboard/dist/img/assets/Monk.png                               # Monk
cp -r ./assets/external/Characters/Monk2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMAW36696WXAEGJ85R.png       # Monk2
cp -r ./assets/external/Characters/Monk2/Faceset.png cmd/client/dist/img/assets/Monk2.png                                # Monk2
cp -r ./assets/external/Characters/Monk2/Faceset.png cmd/dashboard/dist/img/assets/Monk2.png                             # Monk2
cp -r ./assets/external/Characters/Noble/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMW6SJYHMEQJE5VCP0.png       # Noble
cp -r ./assets/external/Characters/Noble/Faceset.png cmd/client/dist/img/assets/Noble.png                                # Noble
cp -r ./assets/external/Characters/Noble/Faceset.png cmd/dashboard/dist/img/assets/Noble.png                             # Noble
cp -r ./assets/external/Characters/OldMan/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMPANM50203S1W2C6Y.png      # OldMan
cp -r ./assets/external/Characters/OldMan/Faceset.png cmd/client/dist/img/assets/OldMan.png                              # OldMan
cp -r ./assets/external/Characters/OldMan/Faceset.png cmd/dashboard/dist/img/assets/OldMan.png                           # OldMan
cp -r ./assets/external/Characters/OldMan2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM1TJ7ZN1CS86HQ8AV.png     # OldMan2
cp -r ./assets/external/Characters/OldMan2/Faceset.png cmd/client/dist/img/assets/OldMan2.png                            # OldMan2
cp -r ./assets/external/Characters/OldMan2/Faceset.png cmd/dashboard/dist/img/assets/OldMan2.png                         # OldMan2
cp -r ./assets/external/Characters/OldMan3/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMJ6HXQYYNFHBP5VTF.png     # OldMan3
cp -r ./assets/external/Characters/OldMan3/Faceset.png cmd/client/dist/img/assets/OldMan3.png                            # OldMan3
cp -r ./assets/external/Characters/OldMan3/Faceset.png cmd/dashboard/dist/img/assets/OldMan3.png                         # OldMan3
cp -r ./assets/external/Characters/OldWoman/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM02YP79VAWSJ676RK.png    # OldWoman
cp -r ./assets/external/Characters/OldWoman/Faceset.png cmd/client/dist/img/assets/OldWoman.png                          # OldWoman
cp -r ./assets/external/Characters/OldWoman/Faceset.png cmd/dashboard/dist/img/assets/OldWoman.png                       # OldWoman
cp -r ./assets/external/Characters/Princess/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMSATBGJ24AN42C7ZE.png    # Princess
cp -r ./assets/external/Characters/Princess/Faceset.png cmd/client/dist/img/assets/Princess.png                          # Princess
cp -r ./assets/external/Characters/Princess/Faceset.png cmd/dashboard/dist/img/assets/Princess.png                       # Princess
cp -r ./assets/external/Characters/RedNinja/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMZEYNNSFMTJ30Q9ND.png    # RedNinja
cp -r ./assets/external/Characters/RedNinja/Faceset.png cmd/client/dist/img/assets/RedNinja.png                          # RedNinja
cp -r ./assets/external/Characters/RedNinja/Faceset.png cmd/dashboard/dist/img/assets/RedNinja.png                       # RedNinja
cp -r ./assets/external/Characters/RedNinja2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMWCFBPC1VH3Z4W2HR.png   # RedNinja2
cp -r ./assets/external/Characters/RedNinja2/Faceset.png cmd/client/dist/img/assets/RedNinja2.png                        # RedNinja2
cp -r ./assets/external/Characters/RedNinja2/Faceset.png cmd/dashboard/dist/img/assets/RedNinja2.png                     # RedNinja2
cp -r ./assets/external/Characters/RedSamurai/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMAPHDQT6NY5NXEYTH.png  # RedSamurai
cp -r ./assets/external/Characters/RedSamurai/Faceset.png cmd/client/dist/img/assets/RedSamurai.png                      # RedSamurai
cp -r ./assets/external/Characters/RedSamurai/Faceset.png cmd/dashboard/dist/img/assets/RedSamurai.png                   # RedSamurai
cp -r ./assets/external/Characters/Samurai/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMHKVM3C5TQZZGNETZ.png     # Samurai
cp -r ./assets/external/Characters/Samurai/Faceset.png cmd/client/dist/img/assets/Samurai.png                            # Samurai
cp -r ./assets/external/Characters/Samurai/Faceset.png cmd/dashboard/dist/img/assets/Samurai.png                         # Samurai
cp -r ./assets/external/Characters/Skeleton/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMGYMVF4HYRQRFQQ23.png    # Skeleton
cp -r ./assets/external/Characters/Skeleton/Faceset.png cmd/client/dist/img/assets/Skeleton.png                          # Skeleton
cp -r ./assets/external/Characters/Skeleton/Faceset.png cmd/dashboard/dist/img/assets/Skeleton.png                       # Skeleton
cp -r ./assets/external/Characters/Villager/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMF9HPPEWQ3HP2X1PE.png    # Villager
cp -r ./assets/external/Characters/Villager/Faceset.png cmd/client/dist/img/assets/Villager.png                          # Villager
cp -r ./assets/external/Characters/Villager/Faceset.png cmd/dashboard/dist/img/assets/Villager.png                       # Villager
cp -r ./assets/external/Characters/Villager2/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMEEF4NN3Y6MMHX2AF.png   # Villager2
cp -r ./assets/external/Characters/Villager2/Faceset.png cmd/client/dist/img/assets/Villager2.png                        # Villager2
cp -r ./assets/external/Characters/Villager2/Faceset.png cmd/dashboard/dist/img/assets/Villager2.png                     # Villager2
cp -r ./assets/external/Characters/Villager3/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRM45BTZQYH9519PQFZ.png   # Villager3
cp -r ./assets/external/Characters/Villager3/Faceset.png cmd/client/dist/img/assets/Villager3.png                        # Villager3
cp -r ./assets/external/Characters/Villager3/Faceset.png cmd/dashboard/dist/img/assets/Villager3.png                     # Villager3
cp -r ./assets/external/Characters/Villager4/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMDF7V4CX148EJCFMJ.png   # Villager4
cp -r ./assets/external/Characters/Villager4/Faceset.png cmd/client/dist/img/assets/Villager4.png                        # Villager4
cp -r ./assets/external/Characters/Villager4/Faceset.png cmd/dashboard/dist/img/assets/Villager4.png                     # Villager4
cp -r ./assets/external/Characters/Woman/SpriteSheet.png cmd/client/dist/img/assets/01GF16HSRMAF049BW351816QPW.png       # Woman
cp -r ./assets/external/Characters/Woman/Faceset.png cmd/client/dist/img/assets/Woman.png                                # Woman
cp -r ./assets/external/Characters/Woman/Faceset.png cmd/dashboard/dist/img/assets/Woman.png                             # Woman

# Map
cp -r ./assets/external/Tilesets/01GHE0TD8VC0HJHAEGTWN0AF44.png cmd/client/dist/img/assets/01GHE0TD8VC0HJHAEGTWN0AF44.png # RuinWall
