// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/elojah/game_03/cmd/api/grpc/api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	entity "github.com/elojah/game_03/pkg/entity"
	dto "github.com/elojah/game_03/pkg/entity/dto"
	room "github.com/elojah/game_03/pkg/room"
	dto1 "github.com/elojah/game_03/pkg/room/dto"
	dto2 "github.com/elojah/game_03/pkg/twitch/dto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("github.com/elojah/game_03/cmd/api/grpc/api.proto", fileDescriptor_6dc96cba8df2a9f1)
}
func init() {
	golang_proto.RegisterFile("github.com/elojah/game_03/cmd/api/grpc/api.proto", fileDescriptor_6dc96cba8df2a9f1)
}

var fileDescriptor_6dc96cba8df2a9f1 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7d, 0xa2, 0x94, 0xf4, 0x04, 0xb4, 0x7d, 0x88, 0x0e, 0x46, 0xba, 0x89, 0xa1, 0x0c,
	0x3d, 0x07, 0x4a, 0x11, 0x03, 0x42, 0x2a, 0x26, 0x48, 0x48, 0x0c, 0x51, 0x24, 0x66, 0xe4, 0x38,
	0x57, 0xc7, 0x60, 0xfb, 0x1d, 0xf1, 0x55, 0x55, 0x37, 0x46, 0x46, 0xfe, 0x0c, 0xfe, 0x04, 0xc6,
	0x8e, 0x8c, 0x19, 0x3b, 0x12, 0x67, 0x61, 0xec, 0xc8, 0x88, 0xee, 0xce, 0x76, 0x1c, 0x68, 0x54,
	0xc3, 0x92, 0xdc, 0xfb, 0xde, 0xf7, 0x73, 0xef, 0x87, 0x1f, 0xed, 0x46, 0xb1, 0x1a, 0x1f, 0x0f,
	0x79, 0x88, 0xa9, 0x27, 0x12, 0x7c, 0x1f, 0x8c, 0xbd, 0x28, 0x48, 0xc5, 0xbb, 0xee, 0xbe, 0x17,
	0xa6, 0x23, 0x2f, 0x90, 0xb1, 0x17, 0x4d, 0x64, 0xa8, 0x0f, 0x5c, 0x4e, 0x50, 0x21, 0xac, 0xe9,
	0xd8, 0xdd, 0x6b, 0x70, 0x11, 0x46, 0xe8, 0x99, 0xcb, 0xe1, 0xf1, 0x91, 0x89, 0x4c, 0x60, 0x4e,
	0x16, 0x72, 0xef, 0x45, 0x88, 0x51, 0x22, 0x16, 0x2e, 0x91, 0x4a, 0x75, 0x5a, 0x5e, 0x3e, 0x5e,
	0x5d, 0x83, 0xfc, 0x10, 0x79, 0x22, 0x53, 0xb1, 0x3a, 0xf5, 0x82, 0x2c, 0x4e, 0x03, 0x15, 0x63,
	0x56, 0x52, 0x0f, 0x5b, 0x51, 0xf6, 0xaf, 0x44, 0xf6, 0x5a, 0x21, 0x32, 0x2c, 0xed, 0x07, 0xad,
	0xec, 0x23, 0x85, 0xcb, 0x59, 0x9e, 0xb6, 0xc6, 0xfe, 0xaf, 0x25, 0x4d, 0xd6, 0x35, 0x5e, 0xd1,
	0xd2, 0x04, 0x31, 0x35, 0x3f, 0xed, 0x32, 0x18, 0xbb, 0x7e, 0x3f, 0x14, 0x49, 0xf2, 0x8f, 0x48,
	0x23, 0xcb, 0x15, 0x83, 0x53, 0x27, 0xb1, 0x0a, 0xc7, 0x06, 0x3a, 0xc2, 0x24, 0xc1, 0x13, 0x8b,
	0x3d, 0xfa, 0x7c, 0x9d, 0x5e, 0x3b, 0xec, 0xbf, 0x86, 0x03, 0x4a, 0xdf, 0xc4, 0xb9, 0xea, 0x99,
	0x76, 0x01, 0xf8, 0x48, 0x21, 0x5f, 0x08, 0x03, 0xf1, 0xd1, 0xbd, 0xf3, 0x97, 0x96, 0x4b, 0x78,
	0x46, 0x37, 0xfd, 0x89, 0x08, 0x94, 0x38, 0xac, 0xc6, 0x0a, 0xdb, 0xbc, 0xfc, 0x32, 0xb5, 0xe4,
	0xee, 0x70, 0xbb, 0x8a, 0xbc, 0x5a, 0x45, 0xde, 0xd3, 0xab, 0x08, 0xcf, 0xe9, 0x2d, 0xfd, 0xde,
	0x82, 0xbd, 0x5b, 0xe7, 0xa8, 0x35, 0x9d, 0x7a, 0xe7, 0x32, 0x39, 0x97, 0xb0, 0x4b, 0x3b, 0x36,
	0x7b, 0xdf, 0x87, 0x2d, 0xe3, 0xa9, 0x42, 0x4d, 0xd1, 0xaa, 0x90, 0xbe, 0x0f, 0x0f, 0xe8, 0xba,
	0xc6, 0xfb, 0x3e, 0xdc, 0xae, 0xdf, 0xb2, 0xae, 0xcd, 0xa5, 0x38, 0x97, 0xc0, 0xe9, 0x86, 0x8f,
	0x59, 0x26, 0x42, 0xed, 0x6e, 0xbc, 0x71, 0xe9, 0x00, 0xba, 0x04, 0xba, 0xb4, 0xf3, 0x56, 0x8e,
	0x6c, 0x11, 0x4d, 0xfb, 0x8a, 0xa6, 0x77, 0x09, 0xdc, 0xa7, 0x37, 0x6d, 0x9d, 0xe5, 0xb4, 0x37,
	0x2a, 0xaa, 0xe7, 0x2e, 0x8e, 0xc0, 0x28, 0xb5, 0xae, 0x01, 0x62, 0x0a, 0x37, 0xb8, 0xf9, 0xd6,
	0x03, 0xb7, 0x3a, 0x80, 0x47, 0x3b, 0xba, 0x16, 0x73, 0xbb, 0x55, 0x97, 0xa6, 0x43, 0xdd, 0xd6,
	0xf6, 0x1f, 0x4a, 0x2e, 0x2b, 0xc0, 0x17, 0x49, 0xd2, 0x00, 0x74, 0xb8, 0x0c, 0x58, 0x25, 0x97,
	0xd5, 0x4e, 0xbc, 0x32, 0xfb, 0xd2, 0xd8, 0x09, 0x2b, 0x2c, 0xef, 0x44, 0xa5, 0xe5, 0x12, 0x9e,
	0xd0, 0xb5, 0x7e, 0x9c, 0x45, 0xb0, 0x62, 0x00, 0xab, 0x06, 0xf3, 0xe2, 0xe5, 0x74, 0xc6, 0x9c,
	0xf3, 0x19, 0x73, 0x2e, 0x66, 0x8c, 0xfc, 0x9a, 0x31, 0xf2, 0xa9, 0x60, 0xe4, 0x6b, 0xc1, 0xc8,
	0xb7, 0x82, 0x91, 0xb3, 0x82, 0x91, 0xef, 0x05, 0x23, 0xd3, 0x82, 0x91, 0x1f, 0x05, 0x23, 0x3f,
	0x0b, 0xe6, 0x5c, 0x14, 0x8c, 0x7c, 0x99, 0x33, 0xe7, 0x6c, 0xce, 0xc8, 0x74, 0xce, 0x9c, 0xf3,
	0x39, 0x73, 0x86, 0xeb, 0xe6, 0xd5, 0xfd, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0x97, 0xa8,
	0xde, 0x65, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Entity
	ListEntity(ctx context.Context, in *dto.ListEntityReq, opts ...grpc.CallOption) (*dto.ListEntityResp, error)
	// Animation
	CreateAnimation(ctx context.Context, in *entity.Animation, opts ...grpc.CallOption) (*types.Empty, error)
	ListAnimation(ctx context.Context, in *dto.ListAnimationReq, opts ...grpc.CallOption) (*dto.ListAnimationResp, error)
	// PC
	CreatePC(ctx context.Context, in *dto.CreatePCReq, opts ...grpc.CallOption) (*entity.PC, error)
	ListPC(ctx context.Context, in *dto.ListPCReq, opts ...grpc.CallOption) (*dto.ListPCResp, error)
	// stream
	ConnectPC(ctx context.Context, in *entity.PC, opts ...grpc.CallOption) (API_ConnectPCClient, error)
	UpdatePC(ctx context.Context, opts ...grpc.CallOption) (API_UpdatePCClient, error)
	// Entity
	CreateEntity(ctx context.Context, in *entity.E, opts ...grpc.CallOption) (*entity.E, error)
	// Room
	CreateRoom(ctx context.Context, in *room.R, opts ...grpc.CallOption) (*room.R, error)
	ListRoom(ctx context.Context, in *dto1.ListRoomReq, opts ...grpc.CallOption) (*dto1.ListRoomResp, error)
	// Cell
	ListCell(ctx context.Context, in *dto1.ListCellReq, opts ...grpc.CallOption) (*dto1.ListCellResp, error)
	// Twitch
	ListFollow(ctx context.Context, in *dto2.ListFollowReq, opts ...grpc.CallOption) (*dto2.ListFollowResp, error)
	// Ping
	Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ListEntity(ctx context.Context, in *dto.ListEntityReq, opts ...grpc.CallOption) (*dto.ListEntityResp, error) {
	out := new(dto.ListEntityResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateAnimation(ctx context.Context, in *entity.Animation, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateAnimation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListAnimation(ctx context.Context, in *dto.ListAnimationReq, opts ...grpc.CallOption) (*dto.ListAnimationResp, error) {
	out := new(dto.ListAnimationResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListAnimation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreatePC(ctx context.Context, in *dto.CreatePCReq, opts ...grpc.CallOption) (*entity.PC, error) {
	out := new(entity.PC)
	err := c.cc.Invoke(ctx, "/grpc.API/CreatePC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListPC(ctx context.Context, in *dto.ListPCReq, opts ...grpc.CallOption) (*dto.ListPCResp, error) {
	out := new(dto.ListPCResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ConnectPC(ctx context.Context, in *entity.PC, opts ...grpc.CallOption) (API_ConnectPCClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/grpc.API/ConnectPC", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIConnectPCClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_ConnectPCClient interface {
	Recv() (*dto.ListEntityResp, error)
	grpc.ClientStream
}

type aPIConnectPCClient struct {
	grpc.ClientStream
}

func (x *aPIConnectPCClient) Recv() (*dto.ListEntityResp, error) {
	m := new(dto.ListEntityResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) UpdatePC(ctx context.Context, opts ...grpc.CallOption) (API_UpdatePCClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[1], "/grpc.API/UpdatePC", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIUpdatePCClient{stream}
	return x, nil
}

type API_UpdatePCClient interface {
	Send(*entity.PC) error
	CloseAndRecv() (*types.Empty, error)
	grpc.ClientStream
}

type aPIUpdatePCClient struct {
	grpc.ClientStream
}

func (x *aPIUpdatePCClient) Send(m *entity.PC) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIUpdatePCClient) CloseAndRecv() (*types.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(types.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) CreateEntity(ctx context.Context, in *entity.E, opts ...grpc.CallOption) (*entity.E, error) {
	out := new(entity.E)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateEntity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateRoom(ctx context.Context, in *room.R, opts ...grpc.CallOption) (*room.R, error) {
	out := new(room.R)
	err := c.cc.Invoke(ctx, "/grpc.API/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListRoom(ctx context.Context, in *dto1.ListRoomReq, opts ...grpc.CallOption) (*dto1.ListRoomResp, error) {
	out := new(dto1.ListRoomResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListCell(ctx context.Context, in *dto1.ListCellReq, opts ...grpc.CallOption) (*dto1.ListCellResp, error) {
	out := new(dto1.ListCellResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListFollow(ctx context.Context, in *dto2.ListFollowReq, opts ...grpc.CallOption) (*dto2.ListFollowResp, error) {
	out := new(dto2.ListFollowResp)
	err := c.cc.Invoke(ctx, "/grpc.API/ListFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Ping(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/grpc.API/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Entity
	ListEntity(context.Context, *dto.ListEntityReq) (*dto.ListEntityResp, error)
	// Animation
	CreateAnimation(context.Context, *entity.Animation) (*types.Empty, error)
	ListAnimation(context.Context, *dto.ListAnimationReq) (*dto.ListAnimationResp, error)
	// PC
	CreatePC(context.Context, *dto.CreatePCReq) (*entity.PC, error)
	ListPC(context.Context, *dto.ListPCReq) (*dto.ListPCResp, error)
	// stream
	ConnectPC(*entity.PC, API_ConnectPCServer) error
	UpdatePC(API_UpdatePCServer) error
	// Entity
	CreateEntity(context.Context, *entity.E) (*entity.E, error)
	// Room
	CreateRoom(context.Context, *room.R) (*room.R, error)
	ListRoom(context.Context, *dto1.ListRoomReq) (*dto1.ListRoomResp, error)
	// Cell
	ListCell(context.Context, *dto1.ListCellReq) (*dto1.ListCellResp, error)
	// Twitch
	ListFollow(context.Context, *dto2.ListFollowReq) (*dto2.ListFollowResp, error)
	// Ping
	Ping(context.Context, *types.Empty) (*types.Empty, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) ListEntity(ctx context.Context, req *dto.ListEntityReq) (*dto.ListEntityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEntity not implemented")
}
func (*UnimplementedAPIServer) CreateAnimation(ctx context.Context, req *entity.Animation) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAnimation not implemented")
}
func (*UnimplementedAPIServer) ListAnimation(ctx context.Context, req *dto.ListAnimationReq) (*dto.ListAnimationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAnimation not implemented")
}
func (*UnimplementedAPIServer) CreatePC(ctx context.Context, req *dto.CreatePCReq) (*entity.PC, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePC not implemented")
}
func (*UnimplementedAPIServer) ListPC(ctx context.Context, req *dto.ListPCReq) (*dto.ListPCResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPC not implemented")
}
func (*UnimplementedAPIServer) ConnectPC(req *entity.PC, srv API_ConnectPCServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectPC not implemented")
}
func (*UnimplementedAPIServer) UpdatePC(srv API_UpdatePCServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdatePC not implemented")
}
func (*UnimplementedAPIServer) CreateEntity(ctx context.Context, req *entity.E) (*entity.E, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedAPIServer) CreateRoom(ctx context.Context, req *room.R) (*room.R, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (*UnimplementedAPIServer) ListRoom(ctx context.Context, req *dto1.ListRoomReq) (*dto1.ListRoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoom not implemented")
}
func (*UnimplementedAPIServer) ListCell(ctx context.Context, req *dto1.ListCellReq) (*dto1.ListCellResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCell not implemented")
}
func (*UnimplementedAPIServer) ListFollow(ctx context.Context, req *dto2.ListFollowReq) (*dto2.ListFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFollow not implemented")
}
func (*UnimplementedAPIServer) Ping(ctx context.Context, req *types.Empty) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_ListEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListEntityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListEntity(ctx, req.(*dto.ListEntityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Animation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateAnimation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAnimation(ctx, req.(*entity.Animation))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListAnimationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListAnimation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListAnimation(ctx, req.(*dto.ListAnimationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreatePC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.CreatePCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreatePC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreatePC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreatePC(ctx, req.(*dto.CreatePCReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ListPCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListPC(ctx, req.(*dto.ListPCReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ConnectPC_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(entity.PC)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).ConnectPC(m, &aPIConnectPCServer{stream})
}

type API_ConnectPCServer interface {
	Send(*dto.ListEntityResp) error
	grpc.ServerStream
}

type aPIConnectPCServer struct {
	grpc.ServerStream
}

func (x *aPIConnectPCServer) Send(m *dto.ListEntityResp) error {
	return x.ServerStream.SendMsg(m)
}

func _API_UpdatePC_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).UpdatePC(&aPIUpdatePCServer{stream})
}

type API_UpdatePCServer interface {
	SendAndClose(*types.Empty) error
	Recv() (*entity.PC, error)
	grpc.ServerStream
}

type aPIUpdatePCServer struct {
	grpc.ServerStream
}

func (x *aPIUpdatePCServer) SendAndClose(m *types.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIUpdatePCServer) Recv() (*entity.PC, error) {
	m := new(entity.PC)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _API_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.E)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateEntity(ctx, req.(*entity.E))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(room.R)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateRoom(ctx, req.(*room.R))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto1.ListRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListRoom(ctx, req.(*dto1.ListRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto1.ListCellReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListCell(ctx, req.(*dto1.ListCellReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto2.ListFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/ListFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListFollow(ctx, req.(*dto2.ListFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.API/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Ping(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEntity",
			Handler:    _API_ListEntity_Handler,
		},
		{
			MethodName: "CreateAnimation",
			Handler:    _API_CreateAnimation_Handler,
		},
		{
			MethodName: "ListAnimation",
			Handler:    _API_ListAnimation_Handler,
		},
		{
			MethodName: "CreatePC",
			Handler:    _API_CreatePC_Handler,
		},
		{
			MethodName: "ListPC",
			Handler:    _API_ListPC_Handler,
		},
		{
			MethodName: "CreateEntity",
			Handler:    _API_CreateEntity_Handler,
		},
		{
			MethodName: "CreateRoom",
			Handler:    _API_CreateRoom_Handler,
		},
		{
			MethodName: "ListRoom",
			Handler:    _API_ListRoom_Handler,
		},
		{
			MethodName: "ListCell",
			Handler:    _API_ListCell_Handler,
		},
		{
			MethodName: "ListFollow",
			Handler:    _API_ListFollow_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _API_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectPC",
			Handler:       _API_ConnectPC_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdatePC",
			Handler:       _API_UpdatePC_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/elojah/game_03/cmd/api/grpc/api.proto",
}
